controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  jump_controller:
    type: cheetah_ros/JumpController
    feet:
      kp_stand: [ 50., 50., 50. ]
      kd_stand: [ 2.5, 2.5, 2.5 ]
      kp_swing: [ 700., 700., 150. ]
      kd_swing: [ 7., 7., 7. ]
    gaits:
      trot:
        cycle: 0.64
        offsets: [ 0., 0.5, 0.5, 0. ]
        durations: [ 0.5, 0.5, 0.5, 0.5 ]
      hold:
        cycle: 0.06
        offsets: [ 0., 0., 0., 0. ]
        durations: [ 1., 1., 1., 1. ]
