controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  legs_controller:
    type: unitree_ros/LegsController
  feets_controller:
    type: unitree_ros/FeetController
