controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  base_controller:
    type: cheetah_ros/ControllerBase
  feets_controller:
    type: cheetah_ros/FeetController
    feet:
      kp_stand: [ 0., 0., 0. ]
      kd_stand: [ 7., 7., 7. ]
      kp_swing: [ 500., 500., 500. ]
      kd_swing: [ 7., 7., 7. ]
