controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  base_controller:
    type: cheetah_ros/ControllerBase
  feets_controller:
    type: cheetah_ros/FeetController
    feet:
      kp_stand: [ 1000., 1000., 1000. ]
      kd_stand: [ 10., 10., 10. ]
      kp_swing: [ 700., 700., 150. ]
      kd_swing: [ 7., 7., 7. ]
